defaults:
  - model: pre4_u5_post4
  - metrics: lensless
  - datasets: custom_dir
  - dataloader: base
  - transforms: none
  - _self_
inferencer:
  device_tensors: ["lensless", "psf", "gt"]
  device: auto
  save_path: "reconstructions"
  seed: 1
  from_pretrained: "daminovkamil/lensless-reconstruction"
  pretrained_filename: "model_best.pth"
