_target_: src.logger.WandBWriter
project_name: "lensless-reconstruction"
entity: null
run_name: "noname"
mode: "online"
loss_names: ["loss", "mse_loss", "lpips_loss"] # which losses to log
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B
id_length: 8 # length of the run_id
